-- migrate:down
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `bots` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `channels` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT, MODIFY `bot_id` BIGINT NOT NULL;
ALTER TABLE `messages` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT, MODIFY `channel_id` BIGINT NOT NULL, MODIFY `parent_message_id` BIGINT;
ALTER TABLE `message_processors` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `message_routing_rules` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT, MODIFY `processor_id` BIGINT NOT NULL;
ALTER TABLE `system_configs` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `message_queues` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `connection_logs` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT, MODIFY `channel_id` BIGINT NOT NULL;
ALTER TABLE `api_call_logs` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT, MODIFY `channel_id` BIGINT, MODIFY `processor_id` BIGINT;

SET FOREIGN_KEY_CHECKS = 1;

