// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/sivdead/OmniBotGo/config"
	"github.com/sivdead/OmniBotGo/internal/providers"
)

// Injectors from wire.go:

// InitializeApp 使用Wire进行依赖注入，初始化整个应用程序
func InitializeApp(cfg *config.Config) (*providers.App, error) {
	loggerInterface := providers.NewLogger(cfg)
	server := providers.NewHTTPServer(cfg, loggerInterface)
	grpcserverServer := providers.NewGRPCServer(cfg, loggerInterface)
	serverServer, err := providers.NewRMQServer(cfg, loggerInterface)
	if err != nil {
		return nil, err
	}
	commonDB, err := providers.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	app := providers.NewApp(server, grpcserverServer, serverServer, commonDB, loggerInterface)
	return app, nil
}
